name: ${PROJECT_NAME}

services:
  db:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - ${DBPORT}:5432
    restart: on-failure
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: dmoopw22

  fpm:
    depends_on:
      - db
    build: docker
    image: ${PROJECT_NAME}_img
    pull_policy: never
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/www/moodledata
    restart: on-failure
    hostname: ${PROJECT_NAME}_fpm
    user: 1000:1000
    environment:
      DEMOODLE_PORT: ${WEBPORT}
      DEMOODLE_EMAIL: demoodle@demoodle.org
      DEMOODLE_URL: http://${PROJECT_NAME}.localhost.direct:${WEBPORT}
      PHP_DB_HOST: db
      PHP_DB_PORT: 5432
      PHP_DB_NAME: moodle
      PHP_DB_USER: moodle
      PHP_DB_PASS: dmoopw22

  httpd:
    depends_on:
      - fpm
    image: php:8.0-apache
    volumes:
      - ./moodle:/var/www/html
      - ./fpm.conf:/etc/apache2/conf-available/fpm.conf
    ports:
      - ${WEBPORT}:80
    restart: on-failure
    hostname: ${PROJECT_NAME}_httpd
    user: 1000:1000

  pgadmin:
    profiles: ["dba"]
    depends_on:
      - db
    image: dpage/pgadmin4
    restart: on-failure
    ports:
      - ${PORTBASE}03:80
    environment:
      PGADMIN_DEFAULT_EMAIL: demoodle@demoodle.org
      PGADMIN_DEFAULT_PASSWORD: dmoopw22

  adminer:
    profiles: ["dba"]
    depends_on:
      - db
    image: adminer
    restart: on-failure
    ports:
      - ${PORTBASE}04:8080

volumes:
  dbdata: {}
