name: ${PROJECT_NAME}

services:
  db:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - ${DBPORT}:5432
    restart: on-failure
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: dmoopw22

  web:
    depends_on:
      - db
    build: docker
    image: ${PROJECT_NAME}_img
    pull_policy: never
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/www/moodledata
    networks:
      - default
      - router
    ports:
      - ${WEBPORT}:80
    restart: on-failure
    user: 1000:1000
    environment:
      DEMOODLE_PORT: ${WEBPORT}
      DEMOODLE_EMAIL: demoodle@demoodle.org
      DEMOODLE_URL: https://${PROJECT_NAME}.localhost.direct
      PHP_DB_HOST: db
      PHP_DB_PORT: 5432
      PHP_DB_NAME: moodle
      PHP_DB_USER: moodle
      PHP_DB_PASS: dmoopw22

  pgadmin:
    profiles: ["dba"]
    depends_on:
      - db
    image: dpage/pgadmin4
    restart: on-failure
    ports:
      - ${PORTBASE}03:80
    environment:
      PGADMIN_DEFAULT_EMAIL: demoodle@demoodle.org
      PGADMIN_DEFAULT_PASSWORD: dmoopw22

  adminer:
    profiles: ["dba"]
    depends_on:
      - db
    image: adminer
    restart: on-failure
    ports:
      - ${PORTBASE}04:8080

networks:
  default: {}
  router:
    name: demoodle-router
    external: true

volumes:
  dbdata: {}
