name: demoodle-router

services:
  router:
    container_name: demoodle-router
    build: docker
    image: traefik_localhost
    pull_policy: never
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/traefik

networks:
  default:
    name: demoodle-router
