entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      tls:
        domains:
          - main: demoodle.localhost.direct

providers:
  docker:
    defaultRule: "Host(`{{ trimSuffix `-web-1` .ContainerName }}.localhost.direct`)"
    network: demoodle-router
  file:
    filename: /etc/traefik/dynamic.yml

api:
  insecure: true
